"""
SQLite schema + seeder for the ADAS Test Agent demo.

The database stores 500+ mock ADAS sensor test records generated by
`mock_data.generate_test_records`. It is intentionally lightweight — no ORM —
because the data is read-only from the app's perspective and this keeps
Phase 1 install footprint minimal.
"""

from __future__ import annotations

import json
import os
import sqlite3
from pathlib import Path

from mock_data import generate_test_records

# Database lives next to this file; override via DATABASE_URL=sqlite:///path.db
_DEFAULT_PATH = Path(__file__).parent / "test_data.db"


def _resolve_db_path() -> Path:
    raw = os.environ.get("DATABASE_URL", "").strip()
    if raw.startswith("sqlite:///"):
        return Path(raw.replace("sqlite:///", "", 1))
    if raw.startswith("sqlite://"):
        return Path(raw.replace("sqlite://", "", 1))
    return _DEFAULT_PATH


DB_PATH = _resolve_db_path()


SCHEMA = """
CREATE TABLE IF NOT EXISTS tests (
    test_id               TEXT PRIMARY KEY,
    sensor_type           TEXT NOT NULL,
    scenario              TEXT NOT NULL,
    scenario_tags         TEXT NOT NULL,          -- JSON array
    feature               TEXT NOT NULL,
    result                TEXT NOT NULL,
    confidence_score      REAL NOT NULL,
    detection_distance_m  REAL NOT NULL,
    false_positive_rate   REAL NOT NULL,
    execution_time_ms     INTEGER NOT NULL,
    timestamp             TEXT NOT NULL,           -- ISO 8601 UTC
    vehicle_model         TEXT NOT NULL,
    firmware_version      TEXT NOT NULL,
    notes                 TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_tests_sensor_type ON tests(sensor_type);
CREATE INDEX IF NOT EXISTS idx_tests_result      ON tests(result);
CREATE INDEX IF NOT EXISTS idx_tests_feature     ON tests(feature);
CREATE INDEX IF NOT EXISTS idx_tests_timestamp   ON tests(timestamp);
"""


def get_connection() -> sqlite3.Connection:
    """Return a sqlite3 connection with Row factory enabled."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def seed_database(force: bool = False, count: int = 550) -> int:
    """
    Create schema and seed `count` test records.

    Idempotent by default — if the `tests` table already contains rows, seeding
    is skipped. Pass `force=True` to wipe and reseed.

    Returns the number of rows now in the `tests` table.
    """
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = get_connection()
    try:
        conn.executescript(SCHEMA)
        cur = conn.execute("SELECT COUNT(*) FROM tests")
        existing = cur.fetchone()[0]
        if existing > 0 and not force:
            return existing
        if force:
            conn.execute("DELETE FROM tests")

        records = generate_test_records(count=count)
        conn.executemany(
            """
            INSERT INTO tests (
                test_id, sensor_type, scenario, scenario_tags, feature,
                result, confidence_score, detection_distance_m,
                false_positive_rate, execution_time_ms, timestamp,
                vehicle_model, firmware_version, notes
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                (
                    r["test_id"], r["sensor_type"], r["scenario"],
                    json.dumps(r["scenario_tags"]), r["feature"],
                    r["result"], r["confidence_score"], r["detection_distance_m"],
                    r["false_positive_rate"], r["execution_time_ms"], r["timestamp"],
                    r["vehicle_model"], r["firmware_version"], r["notes"],
                )
                for r in records
            ],
        )
        conn.commit()
        cur = conn.execute("SELECT COUNT(*) FROM tests")
        return cur.fetchone()[0]
    finally:
        conn.close()


def row_to_dict(row: sqlite3.Row) -> dict:
    """Convert a sqlite3.Row into the record dict, parsing scenario_tags JSON."""
    d = dict(row)
    d["scenario_tags"] = json.loads(d["scenario_tags"])
    return d


if __name__ == "__main__":
    n = seed_database(force=True)
    print(f"Seeded {n} records into {DB_PATH}")
